### PR TITLE
128th landmine resprite

### PR DESCRIPTION
**Pull request by 128th**
# Description

Resprited default SS14 land mine to look similar to Fallout frag mine (Fallout 3 and further):
https://static.wikia.nocookie.net/fallout/images/c/c4/FragMine.png/revision/latest?cb=20110209084434

### CODE REVIEW

**Comment by Peptide90** [comment]
Nice work. It looks good. One thing I would say is for consistency, place the new sprites in resources/textures/_nuclear14 rather than overwriting the old ones, as it'll conflict each time we update.

Then just update the mines to use the new path. This will likely be in resources/prototypes/entities/weapons or somewhere like that.

**Comment by Peptide90** [comment]
> > Nice work. It looks good. One thing I would say is for consistency, place the new sprites in resources/textures/_nuclear14 rather than overwriting the old ones, as it'll conflict each time we update.
> > Then just update the mines to use the new path. This will likely be in resources/prototypes/entities/weapons or somewhere like that.
> 
> How should I update paths? I never done this before, so some advices would be good.

Head to Resources\Prototypes\Entities\Objects\Misc
open land_mine.yml
navigate to the following code:
```
  - type: Sprite
    drawdepth: Items
    sprite: Objects/Misc/landmine.rsi
    state: landmine
    ```
Change `    sprite: Objects/Misc/landmine.rsi` to `    sprite: _Nuclear14/Objects/Misc/landmine.rsi` which is likely where your sprite will be living.

**Review by Peptide90 — COMMENTED** [review]
Last error is to do with your .rsi file.

Did you make a meta.json file for it with the names of your files? Just copy paste another simple meta.json and edit it to your own copyright and license details. If you need help ping me.

**Comment by 128th** [comment]
I think it's good to go.

**Pull request merged**
