### PR TITLE
winterized NCR

### PR DESCRIPTION
**Pull request by PatoGrone**
THE 3ST AIRBORNE BATTALION IS HERE!
the NCR now has a complete sprites overhaul that makes them fit better with the new snowyvale:
image
image
here some of the items icons:
image
most of the new NCR clothing has been added to their loadout menu.

plus: 
beanie hat for hobo gameplay enjoyers
image

### CODE REVIEW

**Comment by PatoGrone** [comment]
ready for merge!

**Comment by MrLopLop** [comment]
very beautiful sprites 👍

**Comment by VlaDOS1408** [comment]
why the fuck did you replace an ordinary NKR helmet with a winter one?! You should have created another prototype, not replaced the existing one, considering that you left it! The winter version must have the word "winter" in the ID! Now the winter version will be on the cards instead of the usual one! Anyway, why the hell does the winter version of the NKR helmet have the ID of a regular NKR helmet?!

**Comment by VlaDOS1408** [comment]
The prototype ID must explicitly indicate which helmet the hell it is! Catching to make a mess! Well, specify "Winter", "Green", "Desert" together with "1,2,3"!!!

**Comment by VlaDOS1408** [comment]
Forget about these numbers 1 2 3! You should always specify in the prototype either " " & "Alt", or "$Specific property", "$Specific property"! Change everything, I won't let you shit any more into the already shit-stained code base!

**Review by VlaDOS1408 — CHANGES_REQUESTED** [review]
Bullshit, rework:
- Prototype IDs
- N14ClothingHeadHatNCRHelmetMetal (which was the base PR for NCR before this) should remain in Desert paint, and Winter should be separate.

Everything else is cool.
What should the IDs look like? About the same as now, but instead of `N14ClothingHeadHatWoodBoonie` or `N14ClothingHeadHatNCRHelmetMetal3` it should be `N14ClothingHeadHatBoonieWood`\\`N14ClothingHeadHatNCRHelmetMetalDesert`.

**Comment by PatoGrone** [comment]
> Bullshit, rework:
> 
> * Prototype IDs
> * N14ClothingHeadHatNCRHelmetMetal (which was the base PR for NCR before this) should remain in Desert paint, and Winter should be separate.
> 
> Everything else is cool. What should the IDs look like? About the same as now, but instead of `N14ClothingHeadHatWoodBoonie` or `N14ClothingHeadHatNCRHelmetMetal3` it should be `N14ClothingHeadHatBoonieWood`\`N14ClothingHeadHatNCRHelmetMetalDesert`.

Thanks for the honest comment but jeez no need to be aggresive about it, will fix those thing soon enough

**Comment by VlaDOS1408** [comment]
Thanks
By the way, this is a meme phrase, well, in Russian, of course. Well, like, "Fuck it, redo it." Without negativity.

**Comment by BlueHNT** [comment]
I will agree with the original comment.

Add on to the existing as winter won't be the only thing around.
Make sure the originals stay and just inherit them as new items for the winter version loadout.

**Comment by VlaDOS1408** [comment]
> > Bullshit, rework:
> > 
> > * Prototype IDs
> > * N14ClothingHeadHatNCRHelmetMetal (which was the base PR for NCR before this) should remain in Desert paint, and Winter should be separate.
> > 
> > Everything else is cool. What should the IDs look like? About the same as now, but instead of `N14ClothingHeadHatWoodBoonie` or `N14ClothingHeadHatNCRHelmetMetal3` it should be `N14ClothingHeadHatBoonieWood``N14ClothingHeadHatNCRHelmetMetalDesert`.
> 
> Thanks for the honest comment but jeez no need to be aggresive about it, will fix those thing soon enough

I'm afraid this is impossible, because whenever I want to add something, I come across a huge pile of feces that brings me to a boil for about 2 hours of work. Well, for example, half of all weapon IDs are not made according to the naming rules, fucking empty versions of weapons lie in a fucking recipe folder and are inherited from the base weapon, and not from the weapon whose empty version it should be. I was also delighted with the beautiful ID of the unfinished weapon frame, which had "Incomplete" at the beginning, and then "N14". Well, from what directly prevents me from just taking and doing something that I want, it's completely broken and improperly made furniture, whose hitboxes are so right that it's just fucking amazing. Well, all sorts of 8 varieties of the same rack are also very pleasing.

**Pull request merged**
