### PR TITLE
New Materials

### PR DESCRIPTION
**Pull request by MrLopLop**
# Description
The introduction of new materials and their integration into the game is a further step towards making it more varied and filled with interesting content.
---

# TODO
- [x] Add new ore.
- [x] Add a scrap.
- [x] Add the ability to receive new materials.
- [x] Edit or add recipes using new ingredients.
- [x] Finishing touches before uploading.
- [ ] Pull is ready to load
---

<details><summary><h1>Media</h1></summary>
<p>

Screenshot 2024-09-25 223459
Screenshot 2024-09-25 225307
Screenshot 2024-09-25 225759
Screenshot 2024-09-25 225814
Screenshot 2024-09-25 225830
Screenshot 2024-09-25 225850

</p>
</details>

### CODE REVIEW

**Comment by Partmedia** [comment]
I was curious why these added new materials (e.g. `ScrapSteel`) instead of using the existing materials (e.g. `Steel`). Was this to prevent scrap items from being inserted into `MaterialStorage` components that accepted `Steel` but aren't supposed to accept scrap?

**Comment by MrLopLop** [comment]
> I was curious why these added new materials (e.g. `ScrapSteel`) instead of using the existing materials (e.g. `Steel`). Was this to prevent scrap items from being inserted into `MaterialStorage` components that accepted `Steel` but aren't supposed to accept scrap?

if you put an existing steel instead of a scrapSteel, then when you try to put a scrap in a workbench, it magically turns into sheets of steel.

**Comment by Partmedia** [comment]
Thanks for your input. There are `EntityWhitelists` that you can use on lathe components to prevent inserting junk, or limit inputs to fully formed sheets. That would have allowed using the same material for the scrap, and for example, letting the scrapping forge use `MaterialReclaimer` instead of being a lathe with a bunch of duplicate recipes.

**Comment by MrLopLop** [comment]
It is worth noting that this was my first major prototyping experience, now I know more than then, thank you for your comments.

**Pull request merged**
