### PR TITLE
Species job blacklist

### PR DESCRIPTION
**Pull request by Vonsant**
Blocks the ability of ghouls roundstarting to become members of the brotherhood of steel and residents of shelters.
I'm assuming this needs a little more testing than I've done. It works fine at first glance, but it's very old code.

Taken from here:
https://github.com/space-wizards/space-station-14/pull/17930#issuecomment-1629131864
from this commit
https://github.com/KasianenkoViacheslavMiki/space-station-14/commit/21977197fc71702f444c905095d15727e63b3457
by @KasianenkoViacheslavMiki

https://github.com/user-attachments/assets/484e83d5-6914-4eb5-a7b0-75cd8f25e761

### CODE REVIEW

**Comment by PatoGrone** [comment]
Thats cool has fuck but the midwest Brotherhood is actually open to recruits super mutants and ghouls, the Washington Brotherhood is the mutant hater one.

**Comment by LovelyLophi** [comment]
This should effect the Washington brotherhood only.

**Comment by Vonsant** [comment]
okay then

**Comment by BlueHNT** [comment]
> Thats cool has fuck but the midwest Brotherhood is actually open to recruits super mutants and ghouls, the Washington Brotherhood is the mutant hater one.

That would be factually wrong. They don't openly 'HATE' mutants. But they do not invite them into their ranks.

**Review by BlueHNT — CHANGES_REQUESTED** [review]
MidWest BS are not as friendly as you thought. They are allowed within the lower ranks, but are disallowed from being Paladins, Sentinels or Commanders and such.

**Pull request merged**
