### PR TITLE
Middle-major crafting update

### PR DESCRIPTION
**Pull request by VlaDOS1408**
# Description
I looked at the workbenches and thought they didn't have enough recipes, so I decided to add them. I added 3 new materials for my recipes, namely: Leather, which can be obtained from raw skins in armorbench (temporary solution), raw skins fall from most animals; Chitin - falls from ants (it was before me) and is used in crafting chitin armor; Parts of the radscorpion exoskeleton - now this is also a material which can be used to make insectoid armor and shield. I also added recipes to the weaponbench, although there are much fewer of them, 4 pieces - a bow, 2 types of spears and a machete.

Additionally, I reorganized the codebase a bit. Not too much. Changed the wallet sprite and added some new sprites for the future.

Almost forgot to mention that I added recipes to the crafting menu on "G", namely: mantles & cloak. Also added the "Butcherable" component to some types of leather clothing so that they can be unraveled into leather.

And many more minor changes.

---

# TODO
- [x] Add more armor recipes to armor workbench.
- [x] Add spears & bow recipes to weaponbench.
- [x] Add three new crafting materials: Leather, Chitin, Exoskeleton.
- [x] Add many nobody needs changes.
- [ ] Add new/old workbench's constructing recipes - I'll add it one of these days.

---

<details><summary><h1>Media</h1></summary>

ammo workbench

workbench

weapon workbench

armor workbench

tinker workbench

construction
</details>

### CODE REVIEW

**Comment by VlaDOS1408** [comment]
Throw comments here what's wrong and I'll fix it

**Comment by VlaDOS1408** [comment]
Tomorrow/today add normal media

**Comment by VlaDOS1408** [comment]
Sprites for workbench's construction stages create `troder.`

**Comment by Peptide90** [comment]
merge conflict but let me know when its ready for review :) thanks

**Pull request merged**
