### PR TITLE
NPC Taming

### PR DESCRIPTION
**Pull request by JerryImMouse**
# Description

This PR implements the possibility to tame entities, so we can create Fallout dogs, which will follow player that tamed it.
This one affects FactionExceptionComponent by adding new system to its access, i don't think this is a big problem.
I've also added a new folder to Content.Server for nuclear scripts - "_NC"

---

# TODO

- [X] NPCTamingOnTouchBehaviourComponent implementation
- [X] NPCTamingOnTouchSystem implementation

---

<details><summary><h1>Media</h1></summary>
<p>

https://github.com/user-attachments/assets/3a150068-a059-40d2-b514-f334c612e4f9

</p>
</details>

### CODE REVIEW

**Comment by JerryImMouse** [comment]
Made this because @Vonsant asked to

**Comment by JerryImMouse** [comment]
Should mention this PR because it also changes FactionExceptionComponent's access, so we can have merge conflicts
https://github.com/space-wizards/space-station-14/pull/26053

**Comment by Vonsant** [comment]
There is no Fallout without Dogmeat.
image

**Comment by JerryImMouse** [comment]
probably i've tested everything, this one should work correctly

**Pull request merged**
