### PR TITLE
increases projectile speed and  fixes projectiles inheriting velocity of the player

### PR DESCRIPTION
**Pull request by ScyronX**
projectile speed is 1.5x faster and gun projectiles inherit velocity of the grid instead of the player now

### CODE REVIEW

**Comment by LovelyLophi** [comment]
there's no media supplied. what does this look like?

**Comment by ScyronX** [comment]
https://github.com/Vault-Overseers/nuclear-14/assets/166930367/bd596c07-8342-4581-9997-3c588df82be3

its short but it shows both the bullet speed and the bullet no longer carrying player inertia

**Comment by BlueHNT** [comment]
if only there could be changeable bullet speed in the yaml itself

**Comment by ScyronX** [comment]
you can probably redefine the speed base variable in yml with the gun component but due to games buggy collision engine you really dont have a lot of variety and slow bullets are really annoying so having a universal high base speed variable is better people wanted to see how 1.5x feels so I made it 1.5x but I think 2x or more will be better depending on how this change affects live rounds

**Pull request merged**
