### PR TITLE
Port sounds from MS13

### PR DESCRIPTION
**Pull request by Vonsant**
Port weapon and some other sounds from Mojave Sun 13.

### CODE REVIEW

**Review by BlueHNT — COMMENTED** [review]
I notice you put the .50 HMG machinegun sound to the minigun which could be a bit too.. much.

**Comment by Vonsant** [comment]
What is this error?

**Comment by BlueHNT** [comment]
Seems like something is causing a fatal error on map.

**Comment by BlueHNT** [comment]
But this isn't a fault of your own. The master is rn screwed.

**Pull request closed without merging**
