### PR TITLE
Power Armor Movespeed and Stat Bonus Nerf

### PR DESCRIPTION
**Pull request by FungiFellow**
**Description**

Increased Most Movement Speed Penalties and altered Power Armor Stat Bonus from +10 strength to +4 Strength
**Why/Balance**

Power Armor was absolutely nutty with its prior movespeed and the stat bonus was far too much 

(I kept seeing nerds with 1 Strength using power Armor, In all honestly it should have a minimum strength requirement to wear)

### CODE REVIEW

**Comment by OldDanceJacket** [comment]
I've been working with Z and a few others on some armor/gun/melee balance changes on and off again for the past week or two, I think this has a good suggestion in lowering the strength but I disagree with making the speed worse, moving slower is a worse direction to take the power armor in with such a big map.
I think you can go much farther with all of these changes and just lower the resists as well! Here let me share what we have drafted.

> 
> t-45 power armor 10 -> 8
> 
> blunt 60 -> 50%
> slash 60 -> 50%
> piercing 50 -> 45%
> heat 45 
> radiation 60 -> moved to helmets, made 70
> stamina 25 -> 0
> explosion 50 -> 35%
> speed decrease 15 -> 10%
> strength 10 -> 2
> endurance 0 -> 2
> reflection 15% -> 10%
> 
> t-60 power armor 10 -> 8
> 
> blunt 65 -> 55%
> slash 70 -> 55%
> piercing 50
> heat 60 ->50%
> radiation 70 -> moved to helmets
> stamina 25 -> 0
> explosion 65 -> 35%
> speed decrease 10
> strength 10 -> 2
> endurance 0 -> 2
> reflection 20% -> 10%
> 
> t-51 power armor 10 -> 8
> 
> blunt 60 -> 55%
> slash 70 -> 55%
> piercing 55 -> 50%
> heat 55 -> 50%
> radiation 70 -> moved to helmets
> stamina 25 -> 0
> explosion 60 -> 35%
> speed decrease 10 -> 8%
> strength 10 -> 2
> endurance 0 -> 2
> reflection 20% -> 15%
> 
> t-51bc paladin commander 10 -> 8
> 
> blunt 65 -> 60%
> slash 75 -> 60%
> piercing 65 -> 60%
> heat 60
> radiation 70 -> moved to helmets
> stamina 25 -> 0
> explosion 70 -> 35%
> speed decrease 8
> strength 10 -> 2
> endurance 0 -> 2
> reflection 20% -> 18% 

Essentially I'm all for nerfing the power armor across the board in ways thats good (less resists and less reflection chance, gutting the SPECIAL gain to 4 stat buffs but splitting it to str and end, making it so they have to wear their helmets to be radiation proof...) but also improve some elements of the suits... IE not make the speed worse, lower the point cost of these items in loadout so the roles can buy other items... etc.

If you think this is out of the scope of the PR or you just don't want to do any of these changes, that's fine! I'd still say get rid of the movement speed nerf and make the STR gain all the way down to 2 imo.

**Comment by 6SpadesLuke** [comment]
brotherhood of FRAUDS update

**Comment by FungiFellow** [comment]
> If you think this is out of the scope of the PR or you just don't want to do any of these changes, that's fine! I'd still say get rid of the movement speed nerf and make the STR gain all the way down to 2 imo.

I'll probably change it to +2 Strength and +2 Endurance, and change the armor values. Thanks for formatting the feedback.

I'm not backing down on a select few movespeed nerfs (Some armors only have 8% slowdown)

**Comment by OldDanceJacket** [comment]
> > If you think this is out of the scope of the PR or you just don't want to do any of these changes, that's fine! I'd still say get rid of the movement speed nerf and make the STR gain all the way down to 2 imo.
> 
> I'll probably change it to +2 Strength and +2 Endurance, and change the armor values. Thanks for formatting the feedback.
> 
> I'm not backing down on a select few movespeed nerfs (Some armors only have 8% slowdown)

Perhaps instead of a sweeping change on values we can go with yours, but instead of also nerfing the t-45 by another 5% just keep it at 15 slowdown along with the  t-60? I agree with the changes to normalizing the slowdown of the armor of the BoS CO to 10% instead of the awkward 8%(they can have a slightly better reflection... And even then that is nerfed for all of them).

**Pull request merged**
