### PR TITLE
Refactor JobBlock code

### PR DESCRIPTION
**Pull request by Zekins3366**
# Description

As they say, why reinvent the wheel?
And even more so if it doesn't work

In short, what was done:
- Remove excess Shitcode
- Add my Shitcode, but the worker

# Media

Video for authenticity
https://github.com/user-attachments/assets/efe11869-639e-448f-83d3-8c9df066cfe1

### CODE REVIEW

**Comment by Peptide90** [comment]
Hey, are you in the discord currently? Not sure if this is a feature of EE already but I will do an upstream merge of EE before merging this if not.

**Review by VMSolidus — CHANGES_REQUESTED** [review]
This PR is completely unecessary, we already have CharacterSpeciesRequirement, as a unified requirement that works on Jobs, Traits, Antags, and Loadouts.

**Comment by Zekins3366** [comment]
It bothered my eyes quite a lot
In general, it does not matter whether this PR is merged, in any case it was done by me on pure enthusiasm and the fact that it did not work for a very long time

I will answer the first question, I do not belong to your circles, because besides that, I already belong to a large number of communities, and this could prevent me

That's all

**Comment by Peptide90** [comment]
> It bothered my eyes quite a lot In general, it does not matter whether this PR is merged, in any case it was done by me on pure enthusiasm and the fact that it did not work for a very long time
> 
> I will answer the first question, I do not belong to your circles, because besides that, I already belong to a large number of communities, and this could prevent me
> 
> That's all

Thank you for your contribution. To save us having to maintain two systems I will close this PR, since the functionality already exists. Maybe we have duplicate code already that can be removed. If you are interested in contributing C# though we do have a number of things to work on :)

**Pull request closed without merging**
