### PR TITLE
training sword

### PR DESCRIPTION
**Pull request by 6SpadesLuke**
A training sword for practice dueling.

# Description

A wooden sword used for practicing dueling. It can be made at a weapons workbench by using 3 planks.

Deals 2 blunt damage (50+ strikes to crit on a humanoid target)
And deals 5 Stamina damage (20+ strikes to down on a humanoid target)

---

<details><summary><h1>Training sword</h1></summary>
</p>

Training Sword

</p>
</details>

### CODE REVIEW

**Comment by Peptide90** [comment]
Looks good however the ID isn't very good imo.

Looking at that file though none of them are good. So I'll likely merge this then change all the IDs to include weapon in the ID.

**Comment by Peptide90** [comment]
Looks good however the ID isn't very good imo.

Looking at that file though none of them are good. So I'll likely merge this then change all the IDs to include weapon in the ID.

**Comment by 6SpadesLuke** [comment]
I dont really know how to do standalone weapons so I need help on this

**Comment by Peptide90** [comment]
The only issue now is the sprites. The inhands sprites are both 32x32 when the total sheet should be 64x64 made up of the 4 directions at 32x32 each.

**Comment by 6SpadesLuke** [comment]
you know I should've made a way to craft this

**Pull request merged**
