### PR TITLE
Wasteland Neutering

### PR DESCRIPTION
**Pull request by ReginaeSpence**
#Neutering of the Wasteland Animals & Minor Buff

This pull request works to remove the issue of overpopulation of the wasteland creatures aside from those stronger than the scalpel. Or the most essential.

---
<details><summary><h1>Media</h1></summary>
# Changelog

:cl:
Safe from neutering:
Deathclaws, chickens, radstags, and brahmin.

It also makes certain threats (deathclaw, assaultron) more.. threat? Movement buff.
 - Deathclaw: from 5 to 5.5
 - Assaultron: from 4 to 6

### CODE REVIEW

**Review by ReginaeSpence — COMMENTED** [review]
Fixed line 140.

**Review by ReginaeSpence — COMMENTED** [review]
Fixed line 202, 203.

**Review by ReginaeSpence — COMMENTED** [review]
Attempt 3, to fix linters. Drastic edition.

**Review by ReginaeSpence — COMMENTED** [review]
I missed a space.

**Review by ReginaeSpence — COMMENTED** [review]
pLS.

**Review by ReginaeSpence — COMMENTED** [review]
Another attemtpt.

**Review by ReginaeSpence — COMMENTED** [review]
Reverted brahmin fix.

**Comment by Peptide90** [comment]
Is this actually an issue? Their chance to breed is set at 0.05%. Could always just stick another zero in there.

**Comment by TheDoktorZ** [comment]
> Is this actually an issue? Their chance to breed is set at 0.05%. Could always just stick another zero in there.

Yes.

**Pull request merged**
