### PR TITLE
NEW WEAPONS + Weapon size balances

### PR DESCRIPTION
**Pull request by MutantMan2040**
SIX NEW MELEE WEAPONS sprited by Alekshhh have been implemented

- Rolling Pin
- Nail Board
- Pool Cue
- Golf Club
- Shovel
- Zappy Shovel

Additionally, Weapon sizes have been rebalanced. most weapons can now fit in backpacks, 

Ginormous weapons like heavy machines guns, miniguns,, and rocket launchers do not fit in backpacks and must be carried or stroed on your backpack/suit storage slot. 

Huge weapons like the antimatter, super sledge, grenade launcher, take up 6 slots

Large weapons like assault rifles, rifles, shotguns, SMGS,  laser guns, Axes, Pool cues take up 4 slots

Pistols and laser/plasma pistols now take up an L shape like revolvers. except for the 9mm which only takes up 2 slots., so you can fit that in your bag nicely

Also wideswing animations for 2 handed weapons have been fixed.

### CODE REVIEW

**Comment by VlaDOS1408** [comment]
Add the suffix N14 to all clone weapons.

**Comment by VlaDOS1408** [comment]
what the fuck
Rifles they shouldn't be so small!

**Comment by BlueHNT** [comment]
> what the fuck Rifles they shouldn't be so small!

It would be overall more beneficial to update the size of their inherited sizes instead of making each one individually bigger. Would save some lines and work.

**Comment by PatoGrone** [comment]
i personally think the only guns that should be capable to fit on a backpack are pistols and SMGs, the rest should be only equipable on suitstorage slot

**Comment by VlaDOS1408** [comment]
Сделай размер пушкам 3x6.
```
- type: Item
  shape:
  - 0,0,2,5 #X1 Y1 X2 Y2
```

**Comment by VlaDOS1408** [comment]
Make all you weapons at normal size please. Or you may to experiment with item shape.

**Comment by MutantMan2040** [comment]
> Make all you weapons at normal size please. Or you may to experiment with item shape.

no lol

**Pull request merged**
