### PR TITLE
Sawed Off Shotgun

### PR DESCRIPTION
**Pull request by MutantMan2040**
HUMUNGUS UPDATE

NEW SAWED OFF SHOTGUN. You can make it by sawing off a shotgun

Some minor but substantial Weapon balances. 

- SMGs are now quite a bit more accurate
- Assault rifles and laser rifles are slightly more innacurate
- Pistols and revolvers have recieved very minor bullet angle variations. (They dont shoot directly straight anymore but close too it)
- Shotguns have a little bit tighter spread
- 45-70 gov reduced by 5 damage
- Laser pistols are much more accurate
- Spears and javelins are a little better
- Spears now hold as many reagents as a javelin.
- Common tools now have increased damage, meaning you can beat someone too death with a wrench more successfully
- Gave BOS new kit, switched out SS14 MREs for N14 C rations in kits
- Sacks have been removed from crafting too stop suckas from looting the entire map.  

Overall the changes were made too make it so all the guns are decent but not super accurate at 5 perception, that way the skill is more noticeable, and not everyone will be laser beaming their guns no matter the perception :P. Characters with high perception will probably not notice much difference. 

Future balance PRS will be released in the future.

### CODE REVIEW

**Comment by MutantMan2040** [comment]
@Peptide90 this one is good to go

**Comment by VlaDOS1408** [comment]
YAML Linet fuck you. Go to repair.

**Comment by VlaDOS1408** [comment]
go fix it*

**Comment by MutantMan2040** [comment]
> YAML Linet fuck you. Go to repair.

Fuck you too bro lol

**Comment by Peptide90** [comment]
You know you didn't have to delete the crafting graph for sacks, just change their recipe from hide: false to hide: true

**Pull request merged**
