### PR TITLE
Mobs shmobs

### PR DESCRIPTION
**Pull request by Vonsant**
# Description

In the process of formation.

---

# TODO

- [x] Change the sprites to the MS13 version.
- [ ] Remake the base mobs.
- [ ] Clean up unnecessary code.
- [ ] Add new mobs.
- [ ] Add spawners.
- [ ] Something else?
---

<details><summary><h1>Media</h1></summary>
<p>

</p>
</details>

### CODE REVIEW

**Comment by 6SpadesLuke** [comment]
hi if u can can you also redo brahmin?
I'd rather not have them pulsate

**Comment by Vonsant** [comment]
image


> hi if u can can you also redo brahmin? I'd rather not have them pulsate

Already done

**Comment by 6SpadesLuke** [comment]
thank you very cool

**Comment by LovelyLophi** [comment]
The molerat should be the pigrat

**Comment by BlueHNT** [comment]
Is this PR stale?
It would be good to clean up the pictures and merge it if you do not wish to continue. Peptide or someone else would pick it up and add make use of the dumped resources at a later point.

**Comment by Peptide90** [comment]
Picking this up now.

**Pull request closed without merging**
